apiVersion: v1
kind: Service
metadata:
  name: universidades-service
spec:
  selector:
    app: universidades
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082         # Puerto expuesto al exterior
      targetPort: 8080   # Puerto real del contenedor (Tomcat está escuchando aquí)
